services:
  api:
    container_name: ${DOCKER_CONTAINER}-api
    build:
      context: ./docker/8.2
      dockerfile: Dockerfile
      args:
        WWWUSER: "${WWWUSER:-1000}"
        WWWGROUP: "${WWWGROUP:-1000}"
    image: avaliacao-php-8.2
    ports:
      - "${DOCKER_PORT:-4087}:8000"
    environment:
      APP_URL: "http://localhost:${DOCKER_PORT:-4087}/"
      DB_HOST: ${DOCKER_CONTAINER}-db
      DB_DATABASE: avaliacao
      DB_USERNAME: root
      DB_PASSWORD: avaliacao
    volumes:
      - ".:/var/www/html"
    depends_on:
      - db
    networks:
      - avaliacao

  db:
    image: mysql:8.4
    container_name: ${DOCKER_CONTAINER}-db
    volumes:
      - dbdata84:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: avaliacao
      MYSQL_DATABASE: avaliacao
      TZ: America/Sao_Paulo
    networks:
      - avaliacao

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${DOCKER_CONTAINER}-pma
    environment:
      - PMA_HOST=${DOCKER_CONTAINER}-db
      - UPLOAD_LIMIT=1000M
    ports:
      - "${DOCKER_PMA_PORT:-4088}:80"
    networks:
      - avaliacao

networks:
  avaliacao:
    name: ${DOCKER_NETWORK:-avaliacao}
    external: true
volumes:
  dbdata84: {}
